### ISSUE TITLE
Couldn't run MOFA2 tutorial for Chromium Single Cell Multiome dataset: SeuratObject error

### ISSUE THREAD

**Issue by aarzalluz** [bioFAM/MOFA2_tutorials#3]
Hello,

I've been trying to follow the [Chromium Single Cell Multiome tutorial](https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/10x_scRNA_scATAC.html), but I'm having some issues with Seurat when I get to the Normalization part:

```
> seurat <- NormalizeData(seurat, 
                        normalization.method = "LogNormalize", 
                        assay = "RNA")

Error in vapply(X = keyed.objects, FUN = function(x) { :
values must be length 1,
but FUN(X[[1]]) result is length 0 
```

I haven't found a workaround yet, but the error seems to be due to some incompatibility with SeuratObject (my error has been reported by other users [here](https://github.com/timoast/signac/issues/872)) and occurs running both the Normalization of RNA and ATAC (which rely on Signac and Seurat, respectively) and Variable Feature Selection (which uses Seurat functions) steps in the tutorial. 

Just FYI, I have tried to create the `seurat` object from the tutorial again using SeuratObject v4.0.4, as suggested in the thread, but it doesn't seem to work. 

Just thought I'd report it here in case there is a quick solution (perhaps providing a working seurat object for download?).

Best,

Ángeles

**Comment by rargelaguet** [comment]
Hi Ángeles,
sorry for my slow reply. Seems like I have to update the tutorial... Could you reach me at the MOFA Slack group (https://biofam.github.io/MOFA2/contact.html)?  Would be useful if you can test a few things while I do the update. Plus, if you are working with 10x Multiome we may have interesting stuff for you :)

**Comment by aarzalluz** [comment]
Hi Ricard, 

Just joined the Slack group :) I'll write to you there.

Happy to run any tests you need -I've tried a lot of stuff at this point, so is there is anything I can do to help debug the tutorial, let me know. 

I have barely started to get my feet wet with MOFA, but I do see that there is a lot of interesting resources on your site!

Ángeles

**Comment by aarzalluz** [comment]
Hi @rargelaguet,

Just a quick update -I found out how to fix this thanks to answers by @kriemo ([here](https://github.com/satijalab/seurat/issues/5676#issuecomment-1111427376)) and @RikLindeboom ([here](https://github.com/satijalab/seurat/issues/5699#issuecomment-1060689856)) to related issues in the Seurat repository. 

Basically, the `key` slots of all assays need to be filled out. Therefore, in order for the tutorial to run successfully, the following needs to happen right after the creation of the `ATAC_promoter` and `ATAC_distal` assays:

```
seurat@assays$ATAC_distal@key <- "atacD_"
seurat@assays$ATAC_promoter@key <- "atacP_"
```

I base one of the single-cell analysis practicals I use with my students off of this tutorial (ofc citing the source!), and finally figured out what was wrong. I just thought I'd leave this here in case someone is experiencing similar issues using MOFA2 -closing this as solved now!

Ángeles

**Comment by rargelaguet** [comment]
Hi @aarzalluz, sorry for not getting back to you on this. I am glad that you fixed it.
